from pydantic import BaseModel

class MediaRoleBase(BaseModel):
    media_role_name: str | None = None
    description: str | None = None
    sort: int | None = None
    is_active: bool | None = None
    lookup: str | None = None

class MediaRoleCreate(MediaRoleBase):
    # media_role_id is auto-generated by the DB
    media_role_name: str
    # description is optional
    sort: int
    lookup: str 
    # is_active is defaulted by the DB

class MediaRoleUpdate(MediaRoleBase):
    pass

class MediaRoleOut(MediaRoleBase):
    media_role_id: str