from datetime import date
from pydantic import BaseModel

class ScheduleDateBase(BaseModel):
    schedule_id: str | None = None
    sd_date: date | None = None
    team_id: str | None = None
    schedule_date_type_id: str | None = None
    notes: str | None = None
    is_active: bool | None = None

class ScheduleDateCreate(ScheduleDateBase):
    # schedule_date_id is auto-generated by the DB
    schedule_id: str
    sd_date: date
    # team_id is optional
    schedule_date_type_id: str
    # notes is optional
    # is_active is defaulted by the DB

class ScheduleDateUpdate(ScheduleDateBase):
    pass

class ScheduleDateOut(ScheduleDateBase):
    schedule_date_id: str