from datetime import date
from pydantic import BaseModel

class ScheduleDateRoleBase(BaseModel):
    schedule_date_id: str | None = None
    media_role_id: str | None = None
    is_required: bool | None = None
    is_preferred: bool | None = None
    assigned_user_id: str | None = None
    is_active: bool | None = None

class ScheduleDateRoleCreate(ScheduleDateRoleBase):
    # schedule_date_role_id is auto-generated by the DB
    schedule_date_id: str
    media_role_id: str
    is_required: bool
    is_preferred: bool
    # assigned_user_id is optional
    # is_active is defaulted by the DB

class ScheduleDateRoleUpdate(ScheduleDateRoleBase):
    pass

class ScheduleDateRoleOut(ScheduleDateRoleBase):
    schedule_date_role_id: str