from pydantic import BaseModel

class TeamUserBase(BaseModel):
    team_id: str | None = None
    user_id: str | None = None
    is_active: bool | None = None

class TeamUserCreate(TeamUserBase):
    # team_user_id is auto-generated by the DB
    team_id: str
    user_id: str
    # is_active is defaulted by the DB

class TeamUserUpdate(TeamUserBase):
    pass

class TeamUserOut(TeamUserBase):
    team_user_id: str