from pydantic import BaseModel

class UserRoleBase(BaseModel):
    user_id: str | None = None
    media_role_id: str | None = None
    proficiency_level_id: str | None = None

class UserRoleCreate(UserRoleBase):
    # user_role_id is auto-generated by the DB
    user_id: str
    media_role_id: str
    proficiency_level_id: str

class UserRoleUpdate(UserRoleBase):
    pass

class UserRoleOut(UserRoleBase):
    user_role_id: str