from datetime import date

from pydantic import BaseModel

class UserAvailabilityBase(BaseModel):
    user_id: str | None = None
    ua_date: date | None = None

class UserAvailabilityCreate(UserAvailabilityBase):
    # user_availability_id is auto-generated by the DB
    user_id: str
    ua_date: date

class UserAvailabilityUpdate(UserAvailabilityBase):
    pass

class UserAvailabilityOut(UserAvailabilityBase):
    user_availability_id: str